/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMyNFT } from "./IMyNFT";
export type { IMyToken } from "./IMyToken";
export type { TokenSale } from "./TokenSale";
