/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type {
  NotQuiteRandom,
  NotQuiteRandomInterface,
} from "../NotQuiteRandom";

const _abi = [
  {
    inputs: [],
    name: "getRandomNumber",
    outputs: [
      {
        internalType: "uint256",
        name: "notQuiteRandomNumber",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tossCoin",
    outputs: [
      {
        internalType: "bool",
        name: "heads",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061020f806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063b41e8cad1461003b578063dbdff2c114610059575b600080fd5b610043610077565b60405161005091906100c7565b60405180910390f35b610061610094565b60405161006e91906100fb565b60405180910390f35b6000806002610084610094565b61008e9190610145565b14905090565b60006001436100a391906101a5565b4060001c905090565b60008115159050919050565b6100c1816100ac565b82525050565b60006020820190506100dc60008301846100b8565b92915050565b6000819050919050565b6100f5816100e2565b82525050565b600060208201905061011060008301846100ec565b92915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601260045260246000fd5b6000610150826100e2565b915061015b836100e2565b92508261016b5761016a610116565b5b828206905092915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b60006101b0826100e2565b91506101bb836100e2565b92508282039050818111156101d3576101d2610176565b5b9291505056fea264697066735822122069618b5ba6d2b06b672372889ba357603829ca39373cf5095be6bafb1a2bb6eb64736f6c63430008120033";

type NotQuiteRandomConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: NotQuiteRandomConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class NotQuiteRandom__factory extends ContractFactory {
  constructor(...args: NotQuiteRandomConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<NotQuiteRandom> {
    return super.deploy(overrides || {}) as Promise<NotQuiteRandom>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): NotQuiteRandom {
    return super.attach(address) as NotQuiteRandom;
  }
  override connect(signer: Signer): NotQuiteRandom__factory {
    return super.connect(signer) as NotQuiteRandom__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NotQuiteRandomInterface {
    return new utils.Interface(_abi) as NotQuiteRandomInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NotQuiteRandom {
    return new Contract(address, _abi, signerOrProvider) as NotQuiteRandom;
  }
}
