/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20VotesSol from "./ERC20Votes.sol";
export * as tokenizedBalletSol from "./TokenizedBallet.sol";
