/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface NotQuiteRandomInterface extends utils.Interface {
  functions: {
    "getRandomNumber()": FunctionFragment;
    "tossCoin()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getRandomNumber" | "tossCoin"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getRandomNumber",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tossCoin", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "getRandomNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tossCoin", data: BytesLike): Result;

  events: {};
}

export interface NotQuiteRandom extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: NotQuiteRandomInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getRandomNumber(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { notQuiteRandomNumber: BigNumber }>;

    tossCoin(
      overrides?: CallOverrides
    ): Promise<[boolean] & { heads: boolean }>;
  };

  getRandomNumber(overrides?: CallOverrides): Promise<BigNumber>;

  tossCoin(overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    getRandomNumber(overrides?: CallOverrides): Promise<BigNumber>;

    tossCoin(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    getRandomNumber(overrides?: CallOverrides): Promise<BigNumber>;

    tossCoin(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getRandomNumber(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tossCoin(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
