/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Ballot__factory } from "./Ballot__factory";
export { IMyToken__factory } from "./IMyToken__factory";
