/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as myErc20Sol from "./MyERC20.sol";
export * as myErc721Sol from "./MyERC721.sol";
export * as tokenSaleSol from "./TokenSale.sol";
